### ISSUE TITLE
Lenovo yoga bios passwd found

### ISSUE THREAD

**Issue by RetroSynthwave** [p0358/lenovo-bios-password-cracker#1]
i cant read the password pattern, whats my password actually  ![Screenshot_macOS-Ventura_2024-04-20_07:33:45](https://github.com/p0358/lenovo-bios-password-cracker/assets/81791107/d11c8787-0243-46af-820f-b0f35359ecdd)

**Comment by p0358** [comment]
I would guess it doesn't work for that particular laptop model then... It didn't work with all the random Lenovo BIOSes I could find online, but it worked for a few, so I decided it was enough to publish it anyways. But sadly it's not a Swiss army knife, as they must have changed how key is stored at some point I guess?

**Comment by RetroSynthwave** [comment]
My Lenovo laptop model is yoga 6 13are05  and Bios version is 1.06  bios backup was made from universal bios utilities 2.0 , if I can send you the back up bios. So u can analyze Data and decrypt password. You're script can be updated with bug fixes and improvement stability

**Comment by p0358** [comment]
I wouldn't count on this working without a proper chip dump with a programmer, idk if software backup would save the NVRAM and such...
